# Use Eclipse Temurin JDK 21 as the base image
FROM eclipse-temurin:21

# Copy the webui directory from the source location
COPY ./webapi/ /webapi/

# Set the working directory to /webui
WORKDIR /webapi

# Execute Gradle commands in order
RUN ./gradlew clean && \
    ./gradlew build
# RUN ./gradlew build -x test
