CREATE DATABASE IF NOT EXISTS mytest;
USE mytest;

DROP TABLE IF EXISTS user;

CREATE TABLE dice(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  value INT NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET=utf8mb4;

GRANT select,insert,update,delete ON mytest.* TO 'myuser'@'%';
